lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variantcomposition_logo_light.png
    - docs/images/nf-core-variantcomposition_logo_light.png
    - docs/images/nf-core-variantcomposition_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variantcomposition_logo_light.png
    - docs/images/nf-core-variantcomposition_logo_light.png
    - docs/images/nf-core-variantcomposition_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Yunjia Zhang
  description: Analyse variant composition
  force: false
  is_nfcore: false
  name: variantcomposition
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - adaptivecard
  version: 1.0.0dev
